"""
Validate the response generated by the AI model. 

Note:
    Author: Elijah Cortez
    Documentation: Elijah Cortez
    Created: March 20, 2025
    Modified: April 17, 2025
"""

import re

def format_response(answer, question):
    """
    Process and format the response returned by either the CSV faiss similarity system or fallback to text 2 text AI model.

    Parameters:
        answer (str): The retrieved from CSV file or AI generated answer related to the user's question.
        question (str): The original question prompted via the user (not directly used, but uses relative context terms).

    Returns:
        str | None: A cleaned and formatted answer prefixed with 'Ocean Vista:', or None then fault to AI fallback if CSV answer not found.
    """
    
    # If answer from CSV not found fallback model
    if not answer:
        return None
    
    # First, try to extract description from format with "description:" label
    if "description:" in answer.lower():
        try:
            description = answer.split("description:")[1].strip()
            return f"{description}"
        except:
            # If parsing fails, continue to other methods
            pass
            
    # Second, try to extract from format with category - subcategory: description
    match = re.search(r'.*?:(.+)', answer)
    if match:
        description = match.group(1).strip()
        return f"{description}"
        
    parts = answer.split(',')
    if len(parts) >= 3:
        # Assume last part is description
        description = parts[2].strip()
        return f"{description}"
    
    # If all extraction methods fail, just return the answer with branding
    return f"{answer}"