from .models import db, User, Hotel, Floor, Room, Booking, FAQ, YesNo, Locations, RoomType, Availability, Saved



def add_layout(hid, base_floor_number, num_floors):
    Floor.add_floor(num_floors, hid, base_floor_number)
    for i in range(num_floors):
        fid = Floor.query.filter_by(hid=hid, floor_number=base_floor_number+i).first().id
        #standard 1-20, base: 150
        Room.add_room(num_rooms=7, fid=fid, hid=hid, base_room_number=1, img="../static/images/roomImgs/standard 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=1, rate=150, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=8, img="../static/images/roomImgs/standard 2.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=1, rate=150, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.Y)
        Room.add_room(num_rooms=3, fid=fid, hid=hid, base_room_number=10, img="../static/images/roomImgs/standard 3.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=1, rate=175, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.Y, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N) # +25 for smoking

        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=13, img="../static/images/roomImgs/standard 4.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=1, rate=250, balcony=YesNo.Y, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N) # +100 for balcony
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=14, img="../static/images/roomImgs/standard 5.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=1, rate=300, balcony=YesNo.Y, city_view=YesNo.Y, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N) # +50 for city view
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=15, img="../static/images/roomImgs/standard 6.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=1, rate=350, balcony=YesNo.Y, city_view=YesNo.N, ocean_view=YesNo.Y, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N) # +100 for ocean view
        
        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=16, img="../static/images/roomImgs/standard2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=2, rate=225, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N) # +75 for 2 beds
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=18, img="../static/images/roomImgs/standard2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=2, rate=225, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.Y)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=19, img="../static/images/roomImgs/standard2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=2, rate=325, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.Y, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=20, img="../static/images/roomImgs/standard2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.STRD, number_beds=2, rate=425, balcony=YesNo.Y, city_view=YesNo.N, ocean_view=YesNo.Y, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)

        #suite 21-30, base: 350
        Room.add_room(num_rooms=3, fid=fid, hid=hid, base_room_number=21, img="../static/images/roomImgs/suite 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=1, rate=350, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=24, img="../static/images/roomImgs/suite 2.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=1, rate=500, balcony=YesNo.Y, city_view=YesNo.Y, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=25, img="../static/images/roomImgs/suite 3.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=1, rate=550, balcony=YesNo.N, city_view=YesNo.Y, ocean_view=YesNo.Y, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=26, img="../static/images/roomImgs/suite 4.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=1, rate=350, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.Y)

        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=27, img="../static/images/roomImgs/suite2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=2, rate=425, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=29, img="../static/images/roomImgs/suite2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=2, rate=500, balcony=YesNo.N, city_view=YesNo.Y, ocean_view=YesNo.N, smoking=YesNo.Y, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=30, img="../static/images/roomImgs/suite2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.ST, number_beds=2, rate=625, balcony=YesNo.Y, city_view=YesNo.N, ocean_view=YesNo.Y, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.Y)

        #deluxe 31 - 40, base: 500
        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=31, img="../static/images/roomImgs/deluxe 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.DLX, number_beds=1, rate=500, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=33, img="../static/images/roomImgs/deluxe 2.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.DLX, number_beds=1, rate=650, balcony=YesNo.Y, city_view=YesNo.Y, ocean_view=YesNo.N, smoking=YesNo.Y, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.Y)
        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=35, img="../static/images/roomImgs/deluxe 3.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.DLX, number_beds=1, rate=700, balcony=YesNo.Y, city_view=YesNo.N, ocean_view=YesNo.Y, smoking=YesNo.Y, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.Y)

        Room.add_room(num_rooms=2, fid=fid, hid=hid, base_room_number=37, img="../static/images/roomImgs/deluxe2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.DLX, number_beds=2, rate=575, balcony=YesNo.N, city_view=YesNo.N, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=39, img="../static/images/roomImgs/deluxe2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.DLX, number_beds=2, rate=725, balcony=YesNo.Y, city_view=YesNo.Y, ocean_view=YesNo.N, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)
        Room.add_room(num_rooms=1, fid=fid, hid=hid, base_room_number=40, img="../static/images/roomImgs/deluxe2bed 1.jpg", modPath="/static/assets/highly_detailed_opti_0225234237_texture.glb", room_type=RoomType.DLX, number_beds=2, rate=775, balcony=YesNo.Y, city_view=YesNo.N, ocean_view=YesNo.Y, smoking=YesNo.N, available=Availability.A, max_guests=4, wheelchair_accessible=YesNo.N)



